/* definitions generated by preprocessor, copy into defines.h */
#ifndef	PPINC
#define	_ATMEGA8	// device select: _ATMEGAxxxx
#define	_B1024	// boot size select: _Bxxxx (words), powers of two only
#ifdef	__ICCAVR__
#include	"iom8.h"
#endif
#if	__GNUC__
#include	<avr/io.h>
#endif

/* baud rate register value calculation */
#define	F_CPU 8000000
#define	BAUD_RATE	19200
#define	BRREG_VALUE	25

/* definitions for UART control */
#define	BAUD_RATE_LOW_REG	UBRRL
#define	UART_CONTROL_REG	UCSRB
#define	ENABLE_TRANSMITTER_BIT	TXEN
#define	ENABLE_RECEIVER_BIT	RXEN
#define	UART_STATUS_REG	UCSRA
#define	TRANSMIT_COMPLETE_BIT	TXC
#define	RECEIVE_COMPLETE_BIT	RXC
#define	UART_DATA_REG	UDR

/* definitions for SPM control */
#define	SPMCR_REG	SPMCR
#define	PAGESIZE	64
#define	APP_END	7168
//#define	LARGE_MEMORY

/* definitions for device recognition */
#define	PARTCODE	0x77
#define	SIGNATURE_BYTE_1	0x1E
#define	SIGNATURE_BYTE_2	0x93
#define	SIGNATURE_BYTE_3	0x07

/* indicate that preprocessor result is included */
#define	PPINC
#endif
